services:
  db:
    image: mysql:8.0
    container_name: serwis_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: serwis_db
      MYSQL_USER: serwis_user
      MYSQL_PASSWORD: serwis_password
    ports:
      - "3306:3306"
    volumes:
      - ./serwis_telefon__w.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: serwis_web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

volumes:
  db_data:
