apiVersion: apps/v1
kind: Deployment
metadata:
  name: moja-aplikacja
  labels:
    app: moja-aplikacja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moja-aplikacja
  template:
    metadata:
      labels:
        app: moja-aplikacja
    spec:
      containers:
      - name: kontener-aplikacji
        # Obraz z Docker Hub 
        image: karolgrabowski002/serwis-telefonow:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"      # 250m = 0.25 rdzenia CPU
          limits:
            memory: "128Mi"
            cpu: "500m"      # Limit do 0.5 rdzenia CPU
---
apiVersion: v1
kind: Service
metadata:
  name: moja-aplikacja-service
spec:
  type: NodePort
  selector:
    app: moja-aplikacja
  ports:
    - port: 80
      targetPort: 80
