apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "TUTAJ_WPISZ_HASLO" # <-- Zmień to przed uruchomieniem
        - name: MYSQL_DATABASE
          value: "serwis_db"
        - name: MYSQL_USER
          value: "serwis_user"
        - name: MYSQL_PASSWORD
          value: "TUTAJ_WPISZ_HASLO" # <-- Zmień to przed uruchomieniem
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
