name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 1. Budujemy obraz lokalnie w pamięci GitHub Actions (jeszcze go nie wysyłamy na Docker Huba!)
      - name: Build Docker image locally
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/serwis-telefonow:test-scan

      # 2. Skanujemy zbudowany obraz narzędziem Trivy
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/serwis-telefonow:test-scan'
          format: 'table'
          exit-code: '0' # Ustaw '1' jeśli chcesz, by krytyczne luki blokowały build. Na razie '0', żeby sprawdzić raport.
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # 3. Jeśli skanowanie przeszło pomyślnie, wypychamy właściwy obraz na Docker Hub
      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/serwis-telefonow:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/serwis-telefonow:${{ github.sha }}
